name: Email Step Test

# Trigger on push to main branch
on:
  push:
    branches:
      - main
  workflow_dispatch:   # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 23f3004096@ds.study.iitm.ac.in
        run: echo "Hello, world!"
